1.- Crea una lista de números secuenciales con el valor mínimo de 10 y el valor máximo 39 <br>
convierte esta lista en una lista o matriz de 2 dimensiones (3 filas por 10 columnas) <br>
muestra por pantalla el valor del elemento de la esquena superior derecha de la matriz

In [1]:
import numpy as np

In [2]:
#un vector del 10 al 39
array = np.arange(10,40)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [7]:
#transformo a un array de dos dimensiones de 3 filas y 10 columnas
array_two_dimension = array.reshape(3,10)
array_two_dimension

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [8]:
#valor de la esquina superior derecha
array_two_dimension[0,9]

19

2.- Crea un array de una dimensión con 9 valores enteros aliatorios entre 0 y 100 <br>
convierte ese array en una matriz de 2 dimensiones 3 filas y 3 columnas <br>
Muestra por pantalla el valor del elemento de la matriz, de la esquina inferior derecha

In [9]:
#array random de 9 valores entre 0 y 100
array_random = np.random.randint(0,101,9)
array_random

array([75, 79, 45,  3, 69,  7, 41, 82, 81])

In [11]:
#paso a una matriz de 2 dimensiones 3x3
two_dimension = array_random.reshape(3,3)
two_dimension

array([[75, 79, 45],
       [ 3, 69,  7],
       [41, 82, 81]])

In [13]:
#mostrar elemento de la esquina inferior derecha
two_dimension[2,2]

81