In [1]:
import numpy as np

In [5]:
np.random.rand(5) #entre 0 y 1 por defecto

array([0.80270999, 0.21009226, 0.68927094, 0.50345047, 0.53948405])

In [8]:
np.random.rand(3,4) # dos dimensiones

array([[0.82273396, 0.03717512, 0.69289605, 0.4468683 ],
       [0.33301127, 0.16509779, 0.13408715, 0.13093532],
       [0.80700287, 0.56662217, 0.59068569, 0.19210631]])

In [9]:
np.random.randn(4) #cuatro elementos con distribución normal, valores tanto negativos como positivos

array([ 0.79264744,  0.35277683, -0.44762983, -1.30759597])

In [11]:
2.5*np.random.randn(4,2)

array([[-5.46253508, -2.28082144],
       [ 2.20584143, -2.72430225],
       [ 3.41576393,  5.12066668],
       [-6.40258033, -3.63291379]])

# Números aleatorios enteros, randint

In [14]:
np.random.randint(1,20) #entre 1 y 19

7

In [15]:
np.random.randint(1,20,100)

array([ 8, 17, 18,  4,  9,  1, 15, 19, 12,  8,  7, 14,  1, 17,  2, 19, 11,
        4,  7, 10,  3, 14, 17,  2,  1,  5,  7, 17,  3, 15,  2, 11, 14, 13,
        5,  2,  1, 18,  3,  1,  3, 19,  3,  4,  9, 11, 10,  6, 13,  9,  6,
       11, 12,  8, 15, 16,  5,  1, 14, 15, 13,  9, 15, 12,  2, 18,  4, 11,
       19, 12, 12, 17,  6,  9, 14,  9,  1, 10, 14, 18,  8,  8, 10,  9,  7,
       14,  2, 19,  3,  7, 19,  5,  6,  7,  8, 10,  5,  7, 12, 17])