In [2]:
import numpy as np #np es numpy

In [3]:
lista = [1,2,3,4]

In [5]:
array = np.array(lista)
array #vector de 4 elementos

array([1, 2, 3, 4])

In [6]:
lista2 =[[1,2,3],[4,5,6],[7,8,9]]
lista2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
array2 = np.array(lista2)
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Funciones arange, ones, zeros y linspace 

In [8]:
 a = np.arange(5) #vector de 0 a un numero menos del indicado
a

array([0, 1, 2, 3, 4])

In [10]:
np.arange(2,10) #ultimo elemento será 10-1

array([2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(2,10,2) #paso 

array([2, 4, 6, 8])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [23]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [24]:
np.ones(3, dtype=int)

array([1, 1, 1])

In [16]:
np.ones((3,5))#3 filas 5 columnas

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.linspace(5,8,50)  #genera 50 elementos entre el 5 y el 8

array([5.        , 5.06122449, 5.12244898, 5.18367347, 5.24489796,
       5.30612245, 5.36734694, 5.42857143, 5.48979592, 5.55102041,
       5.6122449 , 5.67346939, 5.73469388, 5.79591837, 5.85714286,
       5.91836735, 5.97959184, 6.04081633, 6.10204082, 6.16326531,
       6.2244898 , 6.28571429, 6.34693878, 6.40816327, 6.46938776,
       6.53061224, 6.59183673, 6.65306122, 6.71428571, 6.7755102 ,
       6.83673469, 6.89795918, 6.95918367, 7.02040816, 7.08163265,
       7.14285714, 7.20408163, 7.26530612, 7.32653061, 7.3877551 ,
       7.44897959, 7.51020408, 7.57142857, 7.63265306, 7.69387755,
       7.75510204, 7.81632653, 7.87755102, 7.93877551, 8.        ])

In [22]:
np.eye(5) #matriz cuadrada con 1 en la diagonal.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])